name: geoquery_firestore
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  cloud_firestore: ^3.1.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
