name: geoquery_firestore
description: Querying Firestore documents based on geohashes. Allows you to filter documents by range, load more documents with paging and query documents within map bounds.
version: 0.0.6
repository: https://github.com/meanllbrl/geoquery_firestore

environment:
  sdk: ^3.3.4
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.0
  dart_geohash: ^2.0.2
  latlong2: ^0.9.1
  dartdoc: 

dev_dependencies:
  lints: ^4.0.0
  test: 
